apiVersion: v1
kind: Service
metadata:
  name: connexion-api-service
spec:
  type: NodePort
  selector:
    app: connexion-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080