apiVersion: apps/v1
kind: Deployment
metadata:
  name: connexion-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connexion-api
  template:
    metadata:
      labels:
        app: connexion-api
    spec:
      containers:
        - name: connexion-api
          image: connexion-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: OPENSEARCH_HOST
              value: "opensearch:9200"
            - name: OPENSEARCH_USER
              valueFrom:
                secretKeyRef:
                  name: opensearch-secret
                  key: OPENSEARCH_USER
            - name: OPENSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: opensearch-secret
                  key: OPENSEARCH_PASSWORD
