kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: connexion-cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP
      - containerPort: 30920
        hostPort: 30920
        protocol: TCP
